package.json

chore(package): update graphql to version 0.10.3

---

package.json

chore(package): update graphql-tag to version 2.4.2

---

package.json

chore(package): update graphql to version 0.10.5

---

package.json

chore(package): update graphql-tools to version 1.2.3

---

package.json

chore(package): update graphql-server-core to version 1.1.3

---

package.json

chore(package): update graphql-tools to version 2.2.0

---

package.json

chore(package): update graphql-tag to version 2.7.3

---

package.json

chore(package): update apollo-cache-inmemory to version 1.1.7

---

package.json

chore(package): update apollo-client to version 2.2.5

---

package.json

chore(package): update apollo-cache-inmemory to version 1.1.9

---

lib/client/listenToGraphQLMessages.js
lib/server/createGraphQLMethod.js
package.json

chore(package): update eslint to version 4.19.0

---

package.json

chore(package): update graphql-tag to version 2.9.1

---

README.md
client.js
lib/client/apollo-link-meteor-auth.js
lib/client/apollo-link-meteor.js
lib/client/getLoginToken.js
lib/client/graphQLFetcher.js
lib/common/defaults.js
lib/server/contextToFunction.js
lib/server/createGraphQLMethod.js
lib/server/createGraphQLPublication.js
lib/server/createGraphQLRequestHandler.js
lib/server/createHttpServer.js
lib/server/getUserByLoginToken.js
lib/server/setup.js
package.js
package.json
server.js
specs/client.spec.js
specs/client/apollo-link-meteor-auth.spec.js
specs/client/apollo-link-meteor.spec.js
specs/server.spec.js
specs/server/getUserByLoginToken.spec.js
specs/server/helpers.js
specs/server/setup.spec.js

This includes GraphiQL support and authorization in resolvers via HTTP.
Closes https://github.com/Swydo/ddp-apollo/issues/145

feat(http): add http support

---

lib/common/forAwaitEach.js
lib/server/createGraphQLPublication.js

Fixes https://github.com/Swydo/ddp-apollo/issues/148 and prevents possible memory leaks.

fix(subscriptions): add subscription onStop handling

---

specs/client/apollo-client.spec.js
specs/data/resolvers.js
specs/data/typeDefs.js

Closes https://github.com/Swydo/ddp-apollo/issues/103

test(error handling): test if errors arrive at the client correctly

---

client.js
lib/client/graphQLFetcher.js
specs/client/exports.spec.js
specs/client/graphQLFetcher.spec.js

Fixes https://github.com/Swydo/ddp-apollo/issues/199

fix(exports): add Meteor link exports

---

package.json

chore(package): update graphql-tools to version 3.0.5

---

package.json

chore(package): update apollo-cache-inmemory to version 1.2.5

---

package.json

chore(package): update graphql-tools to version 3.1.1

---

package.json

chore(package): update apollo-cache-inmemory to version 1.2.8

---

package.json

chore(package): update graphql to version 14.0.2

---

package.json

chore(package): update apollo-cache-inmemory to version 1.3.9

---

package.json

chore(package): update apollo-client to version 2.4.5

---

package.json

chore(package): update graphql to version 14.1.1

---

package.json

chore(package): update apollo-client to version 2.4.12

---

package.json

chore(package): update apollo-cache-inmemory to version 1.4.2

---

lib/server/createGraphQLMethod.js
lib/server/createGraphQLPublication.js
specs/client/apollo-link-ddp.js
specs/data/resolvers.js
specs/data/typeDefs.js

This is my attempt to solve #267.

Expose ddpConnection in context

---

package.json

chore(package): update eslint-plugin-import to version 2.16.0

---

package.json

chore(package): update sinon to version 7.2.5

---

package.json

chore(package): update sinon to version 7.2.7

---

package.json

closes https://github.com/Swydo/ddp-apollo/pull/309
closes https://github.com/Swydo/ddp-apollo/pull/311
closes https://github.com/Swydo/ddp-apollo/pull/317

chore: update dependencies after xvfb fix

---

package.json

chore(package): update eslint-plugin-import to version 2.18.0

---

package.json

Closes https://github.com/Swydo/ddp-apollo/pull/330

chore(deps): update apollo-client and apollo-cache-inmemory

---

package.json

chore(package): update graphql to version 14.5.3

---

package.json

chore(package): update graphql to version 14.5.7

---

lib/server/forAwaitEach.js

Fixes https://github.com/Swydo/ddp-apollo/issues/348

fix(subscriptions): find async iterators in latest node versions
